### PR TITLE
App setup

### LINKED ISSUE #1: Set Up The Frontend Project
- [ ] Setup a Vue/Quasar App with basic dependencies and placeholder homepage
- [ ] Setup test harness
- [ ] Setup linting configuration
- [ ] Add basic dev instructions for building & running to README

### PR DESCRIPTION
**Pull request by mds1**
Closes #1 

Tasks:
- [x] Setup a Vue/Quasar App with basic dependencies and placeholder homepage
- [x] Install test harnesses (using Cypress for e2e tests and Jest for unit tests)
- [x] Configure Cypress properly with a sample test
- [x] Configure Jest properly with a sample test
- [x] Setup linting configuration: This is about half-complete. I want to review the relationship between ESLint, typescript-eslint, and Prettier to make sure things are set up properly with no conflicts
- [x] Provide instructions to setup git hooks to enforce lint rules
- [x] Provide instructions to setup auto-formatting for VSCode
- [x] Add basic dev instructions for building & running to README
- [x] Configure fonts and color palette

Listing this as a draft until all tasks are complete, but TS-wise it's at a good point for @wildmolasses to check out. Two specific questions I have so far (without having spent time diving into TS yet):
- `babel.config.js`, line 1: Returns a lint error of "no-unsafe-assignment" since we implicitly assign an `any` type. What is the best practice here? Allow this for `require` statements (i.e. ignore lint warning) or figure out the appropriate type and declare it? (This any type also triggers "no-unsafe-member-access" and "no-unsafe-call" in line 10)
- In `OptionsComponent.vue`, you'll see two lines such as `(Array as unknown) as PropType<Todo[]>`
    - I think this first casts the type Array to unknown, then casts unknown to PropType. Why do we do this? (This component was automatically generated as part of the app setup).
    - What does `PropType<Todo[]>` mean? Since `PropType` was imported from Vue this is Vue-specific to an extent, so will need to look into what `PropType` is

### CODE REVIEW

**Comment by mds1** [comment]
Right now the app lives in it's own folder, but I think we can bring that all up and place the files at the repo root, since I don't think we'll really have much else in this repo right? Let me know what you think

**Comment by wildmolasses** [comment]
Way to go @mds1 

I have some ideas on typescript woes, but no guarantees. What about adding `noImplicitAny: false` to your compilerOptions in tsconfig.json.  There's a chance that the quasar tsconfig set it to true behind the scenes. Also we might take a look at [vue doc's recommended ts config](https://vuejs.org/v2/guide/typescript.html#Recommended-Configuration). I'm happy to spend some time tomorrow getting the kinks worked out.

As for `(Array as unknown) as PropType<Todo[]>`, let me look at it in context tomorrow.

**Comment by apbendi** [comment]
Hey @mds1, thanks for tackling this setup! I was able to `npm install` and `npm run dev` without issue. I saw the same TS errors— lets see if @wildmolasses can help us get those resolved today.

> Right now the app lives in it's own folder, but I think we can bring that all up and place the files at the repo root, since I don't think we'll really have much else in this repo right?

Yup, I think we can get rid of the `app` directory and move the contents up a level. This project is just the web app, so no need for subdirectories for other components.

**Comment by mds1** [comment]
Ok everything should be good to go here, with the exception of the TS lint errors we mentioned above. Some notes (all of which are described more in the README):

- Pre-commit hook setup to auto-format code with prettier
- Pre-push hook setup to check non-format related lint issues and run tests
- Hooks will currently fail due to the TS woes, but hooks can by bypassed by adding `--no-verify` to your commits and pushes
- We can tweak the lint and formatting settings as needed, this is just a first go at the initial implementation
- If using VSCode, I defined recommended extensions and settings in the `.vscode` folder, so I assume it will prompt you to install those extensions. I believe settings will be enforced automatically if using VSCode, so files will automatically be formatted on save, etc.

**Comment by mds1** [comment]
TS fixes from @wildmolasses seem to working great! Cleaned up a few other linter things and squashed the commits based on topic. Ready to merge after any final review from either of you

**Pull request merged**
