### PR TITLE
Add "send transaction" functionality

### LINKED ISSUE #54: Move address discovery to initial wallet open

### LINKED ISSUE #57: Display caught send errors with a toast message box

### PR DESCRIPTION
**Pull request by mds1**
Resolves #54
Resolves #57  

Changes:
- Fix API requests to work with kasparovd
- Send tabs now lets you send transactions
- Toasts displayed on success and failure
- Balance page now sorts transactions by number of confirmations

### CODE REVIEW

**Comment by mds1** [comment]
> It also shows up as a toast message, fyi. Are you able to reproduce this?

This is a known issue that @wildmolasses had noticed since it tries to spend the same UTXO that was spent in the first tx. I'm not sure what's involved in fixing it so I'll defer to him. 

> Also, overall things are feeling a bit sluggish, perhaps because I'm using a wallet that has a lot of txs at this point, with prior mining, and now a decent amount of testing. I think that should be resolved once we have caching working for the address discovery piece.

Agreed, it definitely takes quite a bit of time to make all the API calls, but like you said should be resolved once we implement caching

**Comment by wildmolasses** [comment]
Thanks for reviewing Ben! There is stuff under the hood that I've got to iterate on. Matt and I were thinking that this PR would advance the front end <> wallet connection, and I'll file a separate PR to nail down pending tx / utxo state stuff.

Currently we are also making twice the amount of calls needed when the wallet first loads, once for address discovery and again during the wallet balance page component lifecycle on `mounted()`; Matt and I confirmed on Telegram that this is just temporary.

**Comment by apbendi** [comment]
> Matt and I were thinking that this PR would advance the front end <> wallet connection, and I'll file a separate PR to nail down pending tx / utxo state stuff

Got it! All good. So just to clarify— the issue I'm seeing with sending a second tx is not something we can quickly fix in this PR? Fine if so, just want to make sure I understood!

**Comment by wildmolasses** [comment]
> > Matt and I were thinking that this PR would advance the front end <> wallet connection, and I'll file a separate PR to nail down pending tx / utxo state stuff
> 
> Got it! All good. So just to clarify— the issue I'm seeing with sending a second tx is not something we can quickly fix in this PR? Fine if so, just want to make sure I understood!

Correct. I'd recommend at least an additional PR before we put this in front of the Kaspa team's eyes.

**Pull request merged**
